### ISSUE TITLE
Find bottleneck with API

### ISSUE THREAD

**Issue by jlhbaseball15** [Luc-Olsthoorn/Registr#3]
> Figure out a way to max out number of sections pulled for a class

I think this is more accurate: Figure out a way to max out rendering of a large number of permutations of courses which have large sections (try COP3502, IUF1000, CHM2045? or COP4600 together)

**Comment by Luc-Olsthoorn** [comment]
So surprisingly the bottleneck doesn't appear in the DOM operations at all, but instead, it appears before in the shadow DOM. A solution I now plan to implement is a method that generates only a few (100) and adds more based on UI interaction, instead all at once.
