### ISSUE TITLE
[Feature]: Have the search pull up potential autocomplete

### ISSUE THREAD

**Issue by Luc-Olsthoorn** [Luc-Olsthoorn/Registr#41]
Not sure if this is possible but worth the investigate

**Comment by jlhbaseball15** [comment]
If we scrape course numbers from the uf servers and then store them on our server, that could work.

**Comment by Luc-Olsthoorn** [comment]
So I don't think we even need to "scrape" it in the traditional format, because I think that we can just use the string API and leave course code blank, and it returns all the possible classes for the semester. Yeah if we stored this on the database that would be super sick, but it might be possible to just do it front end side on page load with js parsing.
