### ISSUE TITLE
Filter by "Class #"

### ISSUE THREAD

**Issue by markd315** [Luc-Olsthoorn/Registr#59]
The special topics classes all have the same code CIS4930 and are only distinguishable by their section numbers. Why can't I just type in a section number for any course and have it loaded in as the only option for schedule patterning? Seems like a pretty obvious feature to leave out. I'll add that they are changing this to a "Class number" now which is 5 digits: example Class #: 11873 for VR for Social Good.

I might fork and tackle this later tonight. Maybe pick up some other tickets too.

**Comment by Luc-Olsthoorn** [comment]
Hey! It will be awesome if you would contribute! Keep in mind that the reason why we haven't switched over to class number yet is for legacy purposes with the API, which is currently in transition (so summer classes still are using the legacy system). And yes, the feature for the section pinning, is next on my list, and I was planning on tackling it soon.

Also this site is still largely under development and after this weeks public responses, there was good feedback on the ui/ux as well as feature requests. A similar request can be seen in issue #56.  I also wanted to see if there was enough interest from the public to continue developing the website.

If you have any questions about the code or style or technology lmk

**Comment by markd315** [comment]
Your code wasn't too bad so I was able to figure the gist out even without comments.

**Comment by markd315** [comment]
I don't know how to pin a pull request on an issue or vice versa but the branch on my remote is targeting this issue.

**Comment by Luc-Olsthoorn** [comment]
Seen it, and will review it tomorrow. Also you should definitely test it out, and you should be able to just run the docker container to test it out.
