### ISSUE TITLE
Readme not friendly

### ISSUE THREAD

**Issue by Rolstenhouse** [Luc-Olsthoorn/Registr#89]
In order for other devs to open PRs and contribute, it'd be great if you streamlined the dev-setup process in the `README.md`

Low effort

**Comment by jlhbaseball15** [comment]
Oof

**Comment by Luc-Olsthoorn** [comment]
![image](https://user-images.githubusercontent.com/14364864/55731006-65b21d80-59e7-11e9-9f64-faae8112f09c.png)

**Comment by Luc-Olsthoorn** [comment]
Readme is updated. Lmk what else needs to be added

**Comment by Rolstenhouse** [comment]
closed
